[CONFIGURATION]

# OUTPUT
output_file=knowledge-graph.nt
output_format=N-TRIPLES
execution_engine=spark

# MAPPINGS
mapping_partitioning=PARTIAL-AGGREGATIONS

[DataSource1]
mappings=/path/to/mapping/mapping_file.rml.ttl
